spring:
  # ?? ??? ?? : src/main/resources/static
  # classpath : spring src/main ??? ???? ???
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:static/
      add-mappings: true





  ########  JPA Setting
  jpa:
    hibernate:
      ddl-auto: create-drop
      jdbc:
        batch_size: 100
      order_insert: true
      order_update: true

    database: mysql
    database-platform: "org.hibernate.dialect.MySQL8Dialect"

    #sql logger
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql.init.mode: always


  ############ DB Connection
  datasource:
    url: jdbc:mysql://localhost:3306/roomyDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: roomy
    password: roomy1234


########### logger
logging:
  level:
    root: info
    com.roomy:
      config: debug
      controller: debug
      service: debug
      repository: debug

########### File Upload
  servlet:
    multipart:
      enabled: true
      file-size: 2MB
      max-file-size: 20MB
      max-request-size: 20MB
file.upload-dir: c:/bizwork/uploads
real-path: file:///c:/bizwork/uploads/
upload-path: /uploads/**



